//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.18 at 04:28:21 AM MSK 
//


package com.bsu.xmlparsing.jaxbentity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OldCardsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OldCardsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="OrdinaryCard" type="{http://www.example.com/cards}OrdinaryCardType"/>
 *         &lt;element name="GreetingCard" type="{http://www.example.com/cards}GreetingCardType"/>
 *         &lt;element name="Card" type="{http://www.example.com/cards}CardType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OldCardsType", propOrder = {
    "ordinaryCardOrGreetingCardOrCard"
})
public class OldCardsType {

    @XmlElements({
        @XmlElement(name = "OrdinaryCard", type = OrdinaryCardType.class),
        @XmlElement(name = "GreetingCard", type = GreetingCardType.class),
        @XmlElement(name = "Card")
    })
    protected List<CardType> ordinaryCardOrGreetingCardOrCard;

    /**
     * Gets the value of the ordinaryCardOrGreetingCardOrCard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ordinaryCardOrGreetingCardOrCard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrdinaryCardOrGreetingCardOrCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrdinaryCardType }
     * {@link GreetingCardType }
     * {@link CardType }
     * 
     * 
     */
    public List<CardType> getOrdinaryCardOrGreetingCardOrCard() {
        if (ordinaryCardOrGreetingCardOrCard == null) {
            ordinaryCardOrGreetingCardOrCard = new ArrayList<CardType>();
        }
        return this.ordinaryCardOrGreetingCardOrCard;
    }


}
