//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.18 at 04:28:21 AM MSK 
//


package com.bsu.xmlparsing.jaxbentity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrdinaryCardType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrdinaryCardType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.com/cards}CardType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrdinaryCardType")
public class OrdinaryCardType
    extends CardType
{

    @Override
    public String toString() {
        return "OrdinaryCardType{" +
                "theme='" + theme + '\'' +
                ", history=" + history +
                ", valuable='" + valuable + '\'' +
                ", id=" + id +
                ", sent='" + sent + '\'' +
                '}';
    }
}
